In [1]:
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from tqdm import tqdm
from archetypes_re2020.data.remove_extreme_outliers import outliers

In [2]:
with open("/home/thibault.chevilliet@enpc.fr/Documents/2601_archetypes_re2020/data/processed/MC_runs/arch_mi_based_1000_gwp100.pkl", 'rb') as file:
    dict_mi = pickle.load(file)

df_bb = pl.read_parquet("/home/thibault.chevilliet@enpc.fr/Documents/2601_archetypes_re2020/data/processed/MC_runs/2026-5-9-9h53_MC_runs/scores.parquet")
df_var = pl.read_parquet("/home/thibault.chevilliet@enpc.fr/Documents/2601_archetypes_re2020/data/processed/Hb/20-06/scores_climate change_global warming potential (GWP100)_1000.parquet")

In [3]:
import bw2data as bd

bd.projects.set_current("2026-01-13-ecoinvent-3.11-cutoff")
arch_db = bd.Database("2026-4-22-16h25_archetypes_RE2020_BB")
dict_w = {}

for a in tqdm(arch_db) :
    phi = list(a.production())[0]["amount"]
    tmp = {e["input"][1] : e["amount"]/phi for e in tqdm(a.technosphere(),leave = False)}
    dict_w = dict_w | tmp

18:25:19+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.

100%|██████████| 5/5 [00:01<00:00,  3.20it/s]

In [4]:
# ajout d'une colonne poids
df_var = df_var.with_columns(
    poids = pl.col("batiment").replace_strict(dict_w, default = 0.,return_dtype = pl.Float64)
)

In [ ]:
# on a besoin d'afficher des tats pondérées, donc describe() est shunté pour x_var avec numpy

In [ ]:
import math
def weighted_mean_std(values, weights):
    average = np.average(values, weights=weights)
    variance = np.average((values-average)**2, weights=weights)
    return (average, math.sqrt(variance))

In [5]:
usages_col = ["Maison individuelle ou accolée","Bureau","Logement collectif"]

In [18]:
from cmcrameri import cm
cmap = cm.berlin

palette = list(cmap(np.linspace(0.1, 0.9, 3)))

plt.rcParams.update({
    "text.usetex": True,
    "text.latex.preamble": r"\usepackage{amsmath}\usepackage{amssymb}",
    "font.family": "serif",
    "font.serif": "Computer Modern",
})

In [22]:
for i,usage_select in enumerate(usages_col) :
    df_mi_filtered = outliers(pl.DataFrame(list(dict_mi[usage_select][0])[:1000]),"column_0").filter(pl.col("extreme_outliers")==False)
    df_var_filtered = outliers(df_var.filter(pl.col("usage")==usage_select),"score").filter(pl.col("extreme_outliers")==False).select("score","poids")
    df_bb_filtered = outliers(df_bb.filter(pl.col("demand")== "_".join(usage_select.lower().split(" "))),"score").filter(pl.col("extreme_outliers")==False)

    fig,ax = plt.subplots()
    sns.histplot(df_mi_filtered,x= "column_0",ax = ax,label = "Archétype par intensités",stat="probability",
    element = "step",
    edgecolor='face',
    common_bins=False,color="black",common_norm = False, binwidth=20,alpha = 0.6,kde = False)
    sns.histplot(data = df_var_filtered,x = "score", weights="poids",ax = ax,label = "Archétype avec variabilité",stat="probability",
    element = "step",
    # edgecolor='face',
    common_bins=False,color=palette[i],common_norm = False, binwidth=20,alpha = 0.7,kde = False)
    sns.histplot(df_bb_filtered,x="score",ax = ax,label = "Archétype sans variabilité",stat="probability",
    element = "step",
    edgecolor="gray",
    common_bins=False,color=palette[i],common_norm = False, binwidth=20,alpha = 0.2,kde = False)
    ax.set_title(usage_select)
    ax.set_xlabel(r'$\text{kgCO}_2\text{ eq}$')
    ax.set_ylabel("Probabilité")
    ax.legend()
    plt.savefig(f"/home/thibault.chevilliet@enpc.fr/Documents/2601_archetypes_re2020/reports/figures/Distributions/comparaisons archétypes/stats_comp_{usage_select}.pdf",dpi=300)
    plt.clf()
    desc_var = df_var_filtered.select("score").describe().rename({"score": "x_var"})
    desc_bb  = df_bb_filtered.select("score").describe().rename({"score": "x_bb"}).drop("statistic")
    desc_mi  = df_mi_filtered.select("column_0").describe().rename({"column_0": "x_mi"}).drop("statistic")

    stats = pl.concat([desc_var, desc_bb, desc_mi], how="horizontal")
    w_mean, w_std = weighted_mean_std(df_var_filtered["score"].to_list(),df_var_filtered["poids"].to_list())
    w_25 , w_50, w_75 = np.quantile(df_var_filtered["score"].to_list(),q = [0.25,0.5,0.75],weights = df_var_filtered["poids"].to_list(),method="inverted_cdf")
    stats[2,1] = w_mean
    stats[3,1] = w_std
    stats[5,1] = w_25
    stats[6,1] = w_50
    stats[7,1] = w_75
    stats.write_csv(f"/home/thibault.chevilliet@enpc.fr/Documents/2601_archetypes_re2020/reports/tables/comparaisons_archetypes/stats_comp_{usage_select}")

In [16]:
stats

shape: (9, 4)
┌────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ x_var       ┆ x_bb        ┆ x_mi        │
│ ---        ┆ ---         ┆ ---         ┆ ---         │
│ str        ┆ f64         ┆ f64         ┆ f64         │
╞════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 1.061673e6  ┆ 1000.0      ┆ 988.0       │
│ null_count ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 1280.339896 ┆ 1347.898547 ┆ 1706.026686 │
│ std        ┆ 322.869451  ┆ 57.474368   ┆ 682.781829  │
│ min        ┆ 274.891815  ┆ 1165.744077 ┆ 572.351955  │
│ 25%        ┆ 1071.77356  ┆ 1309.368198 ┆ 1237.77041  │
│ 50%        ┆ 1282.808472 ┆ 1343.996428 ┆ 1541.548052 │
│ 75%        ┆ 1471.113892 ┆ 1383.131138 ┆ 1996.7392   │
│ max        ┆ 2817.708984 ┆ 1598.658495 ┆ 4363.980007 │
└────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
# On remplace la colonne x_var avec les valeurs pondérées

In [19]:
pl.DataFrame(x_bb).describe()

shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ column_0    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1000.0      │
│ null_count ┆ 0.0         │
│ mean       ┆ 1347.898547 │
│ std        ┆ 57.474368   │
│ min        ┆ 1165.744077 │
│ 25%        ┆ 1309.368198 │
│ 50%        ┆ 1343.996428 │
│ 75%        ┆ 1383.131138 │
│ max        ┆ 1598.658495 │
└────────────┴─────────────┘

100%|██████████| 5/5 [00:01<00:00,  3.52it/s]

In [41]:
len(dict_w)

79427

In [45]:
dict_w

{'566189_1': 0.0014442047165336203,
 '574565_1': 0.0010055524280477193,
 '562869_1': 0.0034005424180196643,
 '391295_1': 0.002180385152160839,
 '625510_1': 0.0007791014031894399,
 '459945_1': 0.0009928478216493016,
 '601256_1': 0.0004515285787545674,
 '399777_1': 0.0002130596829788662,
 '600205_1': 0.00043161324980569676,
 '579081_1': 0.0003301480824886058,
 '588126_1': 0.002610968298745042,
 '415508_1': 0.0009605712540425113,
 '558264_1': 0.0023503521837072348,
 '567604_1': 0.0003241391470298948,
 '562347_1': 0.0006019236490925906,
 '478887_1': 0.0002614745343890518,
 '572612_1': 0.0006216672941712125,
 '581794_1': 0.0014215424456607674,
 '469069_1': 0.0015751995095335193,
 '487797_1': 0.0008841719317817574,
 '570107_1': 0.00016103947029345408,
 '437840_1': 0.0002867120633156379,
 '505929_1': 0.0027795618593294473,
 '549036_1': 8.67003544756869e-05,
 '594516_1': 0.0008601361899469136,
 '605790_2': 0.0002135747345896129,
 '588186_1': 0.00017391576056212044,
 '606913_1': 0.0005500751202774274,
 '507708_1': 9.45978125071356e-05,
 '352707_1': 0.0004592543529157672,
 '500562_1': 0.0003842285016170045,
 '606837_3': 0.0008187603772169323,
 '394441_1': 0.00027864292141394027,
 '364001_1': 0.00015262696065125874,
 '546481_1': 0.0020193456818673847,
 '494473_1': 0.0006860487455145443,
 '543558_1': 0.00017271397347037824,
 '565277_1': 0.00036225296622514723,
 '616975_1': 0.0002640497924427851,
 '570410_1': 0.00014627465745204997,
 '503142_1': 0.0005396024041922455,
 '601964_1': 0.0004051739337873685,
 '453078_1': 0.00024550793445590546,
 '579999_1': 0.0006455313521358075,
 '614206_1': 0.001699670315463961,
 '505721_1': 0.0005231207526483525,
 '365408_1': 0.00018112648311257361,
 '598282_1': 0.00046560665611497596,
 '537775_1': 0.00037118052747808924,
 '591111_1': 0.00014970833485702768,
 '437040_1': 0.0005299881074583078,
 '587323_1': 0.00029735646327106873,
 '471986_1': 0.00025718243763282967,
 '517549_1': 0.0008009052547110482,
 '533729_1': 0.0006558323843507405,
 '609414_1': 0.0005095577268986905,
 '440899_1': 0.0005140215075251615,
 '609609_1': 0.0013382757685900582,
 '369678_1': 0.0012778430462624505,
 '557223_1': 0.0002982148826223131,
 '426710_1': 0.0018823419534087747,
 '553887_1': 0.0020392610108162556,
 '503000_1': 0.0013305499944288584,
 '615097_1': 0.0005614062557138538,
 '448771_1': 0.0005483582815749385,
 '601171_1': 0.001895046559807192,
 '484555_1': 0.00014284098004707229,
 '553134_1': 0.0002829350181701624,
 '537709_1': 0.0009327584670621919,
 '531329_1': 0.00043951070783714545,
 '469671_1': 0.0005375421977492588,
 '584618_1': 0.00029237763103385106,
 '620660_1': 0.0006987533519129618,
 '583590_11': 0.00010301032214933097,
 '587116_1': 0.011542306596832535,
 '460105_1': 0.0004678385464282115,
 '355684_1': 0.00020825253461189745,
 '424099_1': 0.0003083442309669974,
 '364621_1': 0.0011878806982520349,
 '617038_1': 0.0001527986445215076,
 '353047_1': 0.0005280995848855702,
 '586390_2': 0.00024104415382943448,
 '520294_1': 0.00024722477315839434,
 '539325_1': 0.0001481631800247877,
 '489591_1': 0.0001814698508530714,
 '598401_1': 0.0003510935146589697,
 '572359_1': 0.0022507755389628817,
 '367433_1': 0.0007562674484463383,
 '486069_1': 0.0010244376537750966,
 '507852_1': 0.0017937530763603498,
 '606837_1': 0.0009313849961002009,
 '499624_1': 0.0008199621643086746,
 '584441_1': 0.002242534713190935,
 '589154_1': 0.0005143648752656593,
 '354646_1': 0.00030731412774550405,
 '392756_1': 0.0012944963816765925,
 '346682_1': 0.005674151911725648,
 '545739_1': 0.00026267632148079396,
 '582358_1': 0.009403812309012424,
 '552298_1': 0.0014555358519700466,
 '554536_1': 0.001838047514884562,
 '620407_1': 0.00016138283803395187,
 '617938_1': 0.0003354702824663212,
 '516436_1': 0.0004068907724898573,
 '456458_1': 0.00042285737242300363,
 '589146_1': 0.0003243108309001437,
 '570315_1': 0.000462516346450496,
 '591845_1': 0.0014884991550578326,
 '478762_1': 0.00020516222494741752,
 '571678_1': 0.0010409193053189895,
 '562224_1': 0.0003083442309669974,
 '553994_1': 0.0015808650772517324,
 '605867_1': 0.00042285737242300363,
 '590867_1': 0.00011571492854774847,
 '596565_1': 0.0003066273922645085,
 '565843_1': 0.00017855122505884034,
 '547124_1': 0.00179066276669587,
 '410909_1': 0.0004154749660023016,
 '474581_1': 0.000832666770707092,
 '565752_1': 0.03183121964736476,
 '479868_1': 0.0011878806982520349,
 '561199_1': 0.0003069707600050063,
 '441889_1': 0.0006211522425604658,
 '454312_1': 0.00038886396611372443,
 '569857_2': 0.00010524221246256647,
 '521413_1': 0.000713174797013868,
 '500422_1': 0.00022765281195002144,
 '345329_1': 0.00014764812841404104,
 '489765_1': 0.00011159451566177522,
 '534845_1': 0.0009888990926335774,
 '587479_1': 0.000373069050050827,
 '534952_1': 0.0009425444476663784,
 '523373_1': 0.0007008135583559484,
 '512173_1': 9.23659221939001e-05,
 '576559_2': 0.0002130596829788662,
 '435926_1': 0.00018850888953327567,
 '613199_1': 0.0010285580666610698,
 '450033_1': 0.0004305831465842035,
 '478928_1': 0.0005959147136338797,
 '562596_1': 0.0014447197681443668,
 '351050_1': 0.0004084359273220973,
 '568030_1': 0.00170602261866317,
 '587506_1': 0.002213005087508127,
 '472596_1': 0.00025718243763282967,
 '554744_1': 0.00027057377951224265,
 '598222_1': 0.0008307782481343542,
 '547158_1': 0.0002575258053733274,
 '347537_1': 0.0027821371173831805,
 '394542_1': 0.0005061240494937129,
 '602935_1': 0.00018644868309028903,
 '361157_1': 0.0018716975534533438,
 '552965_1': 0.00043762218526440774,
 '499703_1': 0.00018061143150182698,
 '506637_1': 0.00048483524958285105,
 '617017_1': 0.0005854419975486976,
 '611244_1': 0.002855102762238957,
 '615013_1': 0.0003158983212579483,
 '581702_1': 0.00033220828893159237,
 '551441_1': 0.0008819400414685221,
 '532447_1': 0.0008009052547110482,
 '488842_1': 0.0006333417973481366,
 '394583_1': 0.0007598728097215648,
 '379729_1': 0.0015606063805623641,
 '486080_1': 0.00019262930241924892,
 '363676_1': 0.0001996683410994532,
 '606718_2': 0.0002135747345896129,
 '591753_1': 0.00018198490246381806,
 '438049_1': 0.002031020185044309,
 '594516_2': 0.0012035039304446834,
 '383722_1': 0.0007562674484463383,
 '381366_1': 0.00035590066302593855,
 '558989_1': 0.0002640497924427851,
 '501250_1': 0.00025151686991461644,
 '408283_2': 0.00038766217902198223,
 '478236_1': 0.000616345094193497,
 '492091_1': 0.001463948361612242,
 '525138_1': 0.0064020915215809195,
 '489770_1': 0.0014555358519700466,
 '568410_1': 0.00021460483781110618,
 '614042_2': 0.004576920296965024,
 '584514_1': 0.0018265446955778872,
 '571934_1': 9.288097380464676e-05,
 '446667_4': 0.00030182024389753976,
 '443652_4': 0.00030182024389753976,
 '583654_1': 0.0011559474983857422,
 '475309_1': 0.010152010615557065,
 '578170_1': 0.00018679205083078681,
 '584438_1': 0.00037684609519630246,
 '607010_1': 0.0012829935623699172,
 '617867_1': 0.002035827333411278,
 '594521_1': 0.0016491952576107888,
 '572939_1': 0.00037135221134833817,
 '577219_1': 0.0011245293501301965,
 '366597_1': 0.00029769983101156654,
 '490412_1': 0.0019091246371676007,
 '536238_1': 0.0007368671711082142,
 '550734_1': 0.0011930312143595015,
 '358778_1': 0.0001562323219264853,
 '562929_1': 0.0006455313521358075,
 '529958_1': 0.00028465185687265125,
 '496016_2': 0.0003740991532723203,
 '382088_1': 0.0001996683410994532,
 '493632_1': 0.0012859121881641483,
 '539362_1': 0.00015348538000250315,
 '562409_1': 0.0007560957645760893,
 '364308_1': 0.00041015276602458616,
 '547210_1': 0.00027108883112298934,
 '536562_1': 0.00025151686991461644,
 '530374_1': 0.00042817957240071905,
 '572458_1': 0.0007785863515786933,
 '385543_1': 0.0007562674484463383,
 '595538_1': 0.00023349006353848352,
 '366195_1': 0.001189425853084275,
 '481178_1': 0.00044294438524212316,
 '365334_1': 0.0001996683410994532,
 '546344_1': 0.00011537156080725069,
 '456391_1': 0.0007782429838381955,
 '590860_1': 0.003309893334528253,
 '515483_1': 0.00011914860595272617,
 '457844_1': 0.0006292213844621633,
 '506571_1': 0.0009689837636847066,
 '477574_1': 0.00038628870805999116,
 '532541_1': 0.0006527420746862605,
 '572760_1': 0.005873476885084603,
 '395305_1': 0.0010081276861014525,
 '462490_1': 0.0003701504242565959,
 '567648_1': 0.00027641103110070476,
 '366056_1': 0.00023606532159221682,
 '368917_1': 0.0009047739962116237,
 '489631_1': 0.002925836516781497,
 '511004_1': 0.0003301480824886058,
 '597497_1': 0.00045873930130502054,
 '592745_1': 0.0005452679719104587,
 '506588_1': 0.0009689837636847066,
 '579984_1': 0.0015879041159319368,
 '597401_1': 0.00011365472210476184,
 '562819_1': 0.00039058080481621326,
 '572836_1': 0.0016000936707196078,
 '601221_1': 0.0009313849961002009,
 '588318_1': 0.00019898160561845766,
 '357862_1': 0.0005813215846627245,
 '597481_1': 0.00020241528302343537,
 '504772_1': 9.305265767489565e-05,
 '496172_1': 0.0003055972890430152,
 '473993_1': 0.0006034688039248306,
 '590153_1': 0.000478997997994389,
 '577364_1': 0.035322582832746086,
 '576294_1': 0.00010472716085181982,
 '573887_1': 0.0007554090290950938,
 '473391_1': 0.00029014574072061555,
 '475207_1': 0.00022198724423180827,
 '385542_1': 0.0007562674484463383,
 '582793_1': 0.000553508797682405,
 '595676_1': 0.00012275396722795273,
 '580894_1': 0.0013753594845638173,
 '411824_1': 0.0008738708995668244,
 '583590_15': 0.00010301032214933097,
 '604011_1': 0.0004051739337873685,
 '364119_1': 0.00011365472210476184,
 '622494_1': 0.00396315046082526,
 '559938_1': 0.0011319117565508983,
 '512748_1': 0.00015331369613225425,
 '621398_2': 0.0003110911728909795,
 '583416_1': 0.0011559474983857422,
 '562937_1': 9.665801895012223e-05,
 '537768_1': 0.00019743645078621768,
 '555499_1': 0.0006657900488251759,
 '611448_1': 0.00020962600557388852,
 '580797_1': 0.00012258228335770385,
 '583590_3': 0.00010301032214933097,
 '354646_2': 0.0004309265143247012,
 '350555_1': 0.00021632167651359504,
 '547840_1': 0.00028636869557514014,
 '395451_1': 0.0006717989842838869,
 '592938_3': 0.0003207054696249171,
 '611387_1': 0.0002752092440089626,
 '585312_1': 0.0002733207214362248,
 '568159_1': 0.0007645082742182847,
 '542240_1': 0.0032029342833631977,
 '596670_1': 0.0005751409653337646,
 '435856_1': 0.00023005638613350583,
 '561187_1': 0.00014215424456607672,
 '346691_1': 0.0008385040222955541,
 '421594_1': 0.00016945197993564946,
 '614120_1': 0.00034783152112424087,
 '502330_1': 0.0005596894170113649,
 '590919_1': 0.0005960863975041285,
 '390482_2': 0.003057346361392143,
 '547768_1': 0.0007210722550453168,
 '356871_1': 0.0007598728097215648,
 '572506_2': 0.00021151452814662625,
 '473227_1': 0.0002271377603392748,
 '398879_1': 0.0005694753976155513,
 '597424_1': 0.00017649101861585373,
 '504090_1': 0.00029186257942310443,
 '569902_1': 0.002154632571623506,
 '531344_1': 0.0002523752892658609,
 '606809_2': 0.00031624168899844606,
 '567777_1': 0.004033540847627303,
 '582555_1': 0.0010836685890109618,
 '519513_1': 0.0002808748117271758,
 '609409_1': 0.00013460015427512582,
 '606790_1': 0.002242534713190935,
 '512073_1': 0.0019245761854900002,
 '583590_5': 0.00010301032214933097,
 '536527_1': 0.00024224594092117665,
 '535151_1': 0.0007368671711082142,
 '511991_1': 0.00023005638613350583,
 '406265_1': 0.0004261193659577324,
 '523370_1': 0.0007008135583559484,
 '599228_1': 0.0005541955331634006,
 '625361_1': 5.9917670716860845e-05,
 '552329_2': 0.0022571278421620903,
 '623400_1': 0.0023079462677557602,
 '365736_1': 0.00029357941812559326,
 '598208_1': 0.0021948065972617454,
 '623374_1': 0.00043161324980569676,
 '391261_1': 0.002180385152160839,
 '557232_1': 0.0026416997115195928,
 '519341_1': 0.0005231207526483525,
 '586464_1': 0.00010575726407331313,
 '591138_1': 0.0003550422436746941,
 '567107_1': 0.00032894629539686354,
 '386380_1': 0.0011914860595272617,
 '352557_1': 0.00029186257942310443,
 '559992_1': 0.00048758219150683325,
 '441671_1': 0.0007657100613100269,
 '351872_1': 0.004304286311009794,
 '486054_1': 5.219189655566102e-05,
 '549629_1': 0.0016093645997130475,
 '558356_1': 0.00020224359915318646,
 '462490_2': 0.0007430477904371741,
 '347877_2': 0.00023211659257649244,
 '444676_1': 0.0006144565716207592,
 '589022_1': 0.0003243108309001437,
 '357092_1': 0.0034765983725399204,
 '346416_1': 0.0001812981669828225,
 '580779_1': 0.0002316015409657458,
 '605842_1': 0.0034868994047548532,
 '567747_1': 0.0004348752433404256,
 '558290_1': 0.001168480420913911,
 '481996_1': 0.0016119398577667807,
 '572888_1': 0.002548990421585195,
 '595542_1': 0.00023349006353848352,
 '569857_1': 0.0004865520882853399,
 '470197_1': 0.0004168484369642927,
 '607829_1': 0.00031624168899844606,
 '516503_1': 0.0014745927615676727,
 '548450_1': 0.00023486353450047462,
 '553002_1': 0.0009322434154514453,
 '350553_1': 0.00011966365756347281,
 '473234_1': 0.0007456230484909073,
 '583440_1': 0.0004956513334085309,
 '477456_1': 0.0002154632571623506,
 '481221_1': 0.0016498819930917843,
 '547816_1': 0.00028636869557514014,
 '433909_1': 0.0014404276713881447,
 '598363_1': 0.0015745127740525238,
 '593855_1': 0.00023297501192773686,
 '475340_1': 0.010152010615557065,
 '573801_1': 0.0028224828268916687,
 '624272_1': 0.0004463780626471009,
 '462364_1': 0.004327978685104141,
 '520422_1': 0.0016687672188191616,
 '583590_7': 0.00010301032214933097,
 '512874_1': 0.0006383206295853543,
 '618749_1': 0.00032997639861835686,
 '531448_1': 0.0002872271149263845,
 '503988_2': 8.652867060543801e-05,
 '504789_1': 9.305265767489565e-05,
 '579976_1': 0.000319331998662926,
 '509305_1': 0.0008513803125642204,
 '513783_1': 0.0005068107849747084,
 '347348_1': 0.00010850420599729529,
 '583590_6': 0.00010301032214933097,
 '614157_1': 0.0028911563749912227,
 '441666_1': 0.0003316932373208457,
 '582632_1': 0.001242819536731678,
 '619520_1': 0.0010249527053858433,
 '469227_1': 9.185087058315344e-05,
 '549130_1': 0.00013391341879413025,
 '523182_1': 0.007120073466961756,
 '508402_1': 0.00026439316018328284,
 '605860_1': 0.0006613262681987048,
 '416374_2': 0.00038766217902198223,
 '533750_1': 0.00033959069535229443,
 '524080_1': 0.0011423844726360804,
 '625503_1': 0.0003248258825108903,
 '521207_1': 0.00013150984461064586,
 '623421_1': 0.0007184969969915835,
 '403891_1': 0.0005179702365408859,
 '493499_1': 0.0004168484369642927,
 '383753_1': 0.00041959537888827485,
 '478931_1': 0.00012807616720566817,
 '351872_2': 0.004304286311009794,
 '600253_1': 0.0005305031590690545,
 '615178_1': 0.0003878338628922311,
 '573906_1': 0.0004360770304321678,
 '446858_1': 0.002017628843164896,
 '423274_1': 0.00011743176725023731,
 '557371_1': 0.0034868994047548532,
 '454331_1': 0.001312008136441979,
 '570340_1': 0.0011846187047173061,
 '604781_1': 0.006510424043707966,
 '579145_1': 0.0003397623792225433,
 '570499_1': 0.0003389039598712989,
 '520451_1': 0.00045719414647278064,
 '515554_1': 0.00014627465745204997,
 '458949_1': 0.00041616170148329714,
 '479008_1': 0.001720615747634325,
 '473937_1': 0.0008783346801932954,
 '614042_1': 0.0035670757721610823,
 '460135_1': 0.00010009169635509993,
 '615117_1': 0.0036233880816027167,
 '553044_1': 0.0006465614553573007,
 '606840_2': 0.00031624168899844606,
 '589223_1': 0.001862083256719406,
 '465599_1': 0.0006331701134778877,
 '548433_1': 0.0006439861973035675,
 '596616_1': 0.006510424043707966,
 '496132_1': 0.0005375421977492588,
 '549954_1': 0.0001481631800247877,
 '605808_1': 8.378172868145585e-05,
 '623466_1': 0.0003785629338987913,
 '367412_1': 0.000183530057296058,
 '559985_1': 0.009241742735497476,
 '355077_1': 0.0013197339106031786,
 '606837_2': 0.00031624168899844606,
 '512813_1': 0.0019245761854900002,
 '597584_1': 0.0010289014344015675,
 '504775_1': 9.305265767489565e-05,
 '583590_9': 0.00010301032214933097,
 '570694_1': 0.0022784166420729522,
 '606840_1': 0.0009313849961002009,
 '485412_1': 0.0010215190279808655,
 '622419_1': 0.0004937628108357932,
 '346908_1': 0.00013133816074039698,
 '578262_1': 0.0055968941701136496,
 '418962_1': 0.0007420176872156807,
 '596441_1': 0.0020183155786458913,
 '561241_1': 0.0005184852881516325,
 '604915_1': 0.0019686989401439636,
 '557313_1': 0.0013465165943620046,
 '616882_1': 0.00019743645078621768,
 '584511_1': 0.0006455313521358075,
 '557342_1': 0.00036362643718713836,
 '560876_1': 0.0006657900488251759,
 '607828_1': 0.0009313849961002009,
 '612288_1': 0.002006984443209465,
 '575521_1': 0.00038062314034177793,
 '583590_12': 0.00010301032214933097,
 '488760_1': 0.00026422147631303397,
 '573857_1': 0.00034250932114652545,
 '578031_1': 0.0009573092605077825,
 '433135_1': 9.23659221939001e-05,
 '372051_1': 0.0005329067332525389,
 '504877_1': 0.0001483348638950366,
 '568341_1': 0.0005471564944831963,
 '357211_1': 0.000159665999331463,
 '625489_1': 0.00033959069535229443,
 '612262_3': 0.0004867237721555888,
 '574529_1': 0.0004956513334085309,
 '571773_1': 0.00031624168899844606,
 '566397_1': 0.000187993837922529,
 '440842_1': 0.0004549622561595451,
 '587206_1': 0.0005850986298081999,
 '413720_1': 0.0007948963192523374,
 '614062_1': 0.0012824785107591705,
 '515651_1': 0.013165405906165493,
 '400530_1': 0.00029357941812559326,
 '619388_1': 0.00030130519228679307,
 '548348_1': 0.00043521861108092335,
 '562296_1': 0.0006560040682209895,
 '466657_1': 0.003281393812066938,
 '490539_1': 0.0007313732872602499,
 '574748_1': 0.00024567961832615433,
 '614104_1': 0.0025112199701304403,
 '569822_1': 0.00014215424456607672,
 '522178_1': 0.0010836685890109618,
 '482642_3': 0.0003207054696249171,
 '516438_1': 0.00043161324980569676,
 '347395_1': 0.0021136001266340225,
 '565960_1': 0.00021700841199459058,
 '586257_1': 0.001283336930110415,
 '465454_1': 9.80314899121133e-05,
 '565478_1': 0.0010417777246702338,
 '469750_1': 0.0002580408569840741,
 '356664_1': 0.0017923796053983588,
 '605773_1': 0.0001471330768032944,
 '499556_1': 0.0001435277155280678,
 '446633_1': 9.442612863688673e-05,
 '578173_1': 0.00010404042537082428,
 '606809_1': 0.0009313849961002009,
 '394524_1': 0.00041015276602458616,
 '471530_1': 0.00044672143038759863,
 '562412_1': 0.0007560957645760893,
 '548445_1': 0.00023486353450047462,
 '573837_2': 0.0002135747345896129,
 '552214_1': 0.003055801206559903,
 '523196_1': 0.007200593202108484,
 '351968_1': 0.00019314435402999558,
 '565493_1': 0.00804785310178673,
 '583590_2': 9.957664474435327e-05,
 '579245_1': 0.0007457947323611561,
 '360089_1': 0.001285053768812904,
 '579964_1': 0.000492389339873802,
 '506625_1': 0.001289689233309624,
 '616046_1': 0.0005854419975486976,
 '437127_1': 0.0005299881074583078,
 '625637_1': 0.0013439413363082714,
 '465613_1': 0.0004664650754662204,
 '583590_13': 0.00010301032214933097,
 '581780_1': 0.0006541155456482517,
 '545753_1': 0.0014993152388835121,
 '517576_1': 0.0020313635527848066,
 '601221_2': 0.00031624168899844606,
 '563170_2': 0.000929496473527463,
 '547740_1': 0.0015746844579227729,
 '425558_1': 0.0002535770763576031,
 '580905_1': 0.0011319117565508983,
 '437819_1': 0.0008738708995668244,
 '475190_1': 0.0007255360356717878,
 '549890_2': 9.047739962116237e-05,
 '555408_1': 0.0003055972890430152,
 '549001_1': 0.0005140215075251615,
 '571871_1': 0.000247739824769141,
 '610475_1': 0.0007837368676861598,
 '492743_1': 0.00030954601805873957,
 '601276_1': 0.001140324266193094,
 '595671_1': 0.00012275396722795273,
 '469024_1': 0.0004913592366523087,
 '570257_1': 0.0007057923905931661,
 '613231_1': 0.002249058700260393,
 '623216_1': 0.0004051739337873685,
 '479673_1': 0.00018885225727377345,
 '519334_1': 0.0005234641203888502,
 '566038_1': 0.0002942661536065888,
 '545716_1': 0.0007219306743965612,
 '402189_1': 0.00018078311537207586,
 '592949_1': 0.0007059640744634149,
 '563170_1': 0.000883485196300762,
 '354799_1': 0.0001380338316801035,
 '578253_1': 0.00018456016051755133,
 '603838_1': 0.0011502819306675291,
 '608660_1': 0.0003708371597375915,
 '481332_1': 0.000673000771375629,
 '590191_1': 0.0003066273922645085,
 '471972_1': 0.00020327370237467978,
 '524078_1': 0.0005308465268095522,
 '383800_1': 0.00041959537888827485,
 '404020_6': 0.00017305734121087602,
 '579160_1': 0.0020231227270128605,
 '549134_1': 0.00032585598573238363,

In [51]:
missing = df_var.filter(
    ~pl.col("batiment").is_in(list(dict_w.keys()))
)["batiment"].unique()
print(missing)

shape: (217,)
Series: 'batiment' [cat]
[
	"352869_1"
	"495998_1"
	"478777_1"
	"505810_1"
	"351163_1"
	…
	"431160_1"
	"367644_1"
	"351647_1"
	"488647_1"
	"514648_1"
]